name: With Secrets

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - completed

  workflow_dispatch:

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    concurrency: acctest
    steps:
      - uses: actions/checkout@v4

      - run: echo ${{ tojson(github.event) }}

      - run: echo ${{ github.event.workflow_run.head_branch }}

      - run: echo ${{ secrets.FAKE }} | rev
