name: With Secrets

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - completed

  workflow_dispatch:

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    concurrency: acctest
    if: ${{ github.event.workflow_run.event != 'push' }}
    steps:
      - uses: actions/checkout@v4

      - name: add pr check
        uses: actions/github-script@v4
        if: ${{ github.event.workflow_run.event != 'pull_request' }}
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                github.checks.create({
                    name: 'accptance tests',
                    head_sha: '${{ github.event.workflow_run.head_commit.id }}',
                    status: 'queued',
                    output: {
                        title: 'This is a title',
                        summary: 'This is a summary'
                    },
                    owner: context.repo.owner,
                    repo: context.repo.repo
                })

      - run: echo ${{ tojson(github.event) }}

      - run: echo ${{ secrets.FAKE }} | rev
